### PR TITLE
fix: specify path

### LINKED ISSUE #153: [urgent] requires upgrading Transifex CLI tool
I have received a notification from transifex that the old Transifex API used in charites will no longer work after 12 February 2023. It requires to be upgraded to new API/CLI by that time.

image

I will not work with this issue since I am no longer a member of this charites project.

@hfu @ubukawa Please assign a right person and upgrade the transifex CLI tool. If you need to transfer my owner permission of transifex to someone else, I am willing to do so. Please let me know to whom I will transfer permission.

references
- [announcement](https://community.transifex.com/t/important-reminder-api-tx-cli-deprecation/3202?utm_campaign=Product%20Updates&utm_medium=email&_hsmi=243729257&_hsenc=p2ANqtz-_8lbGM1PN80IN5IQQHKuAEuLyNfHrmn4rsS9cxw2-1hDFtrf6OvGlASkD8l5gHzCVzFOKswBwmqm2J70IaNazSJfPeyg&utm_content=243729257&utm_source=hs_email)
- [CLI](https://developers.transifex.com/docs/using-the-client?utm_campaign=Product%20Updates&utm_medium=email&_hsmi=243729257&_hsenc=p2ANqtz-9NJgtglF9X6wAEjLcYwNriMx2OYveuV21TZHwc70yEs9hhNWpxcsosdaxk656CRYIz-LBj3hR6eMZoQ5PFrq8M1dOL-w&utm_content=243729257&utm_source=hs_email)

### PR DESCRIPTION
**Pull request by JinIgarashi**
Thank you for submitting a pull request!

## Description

@ubukawa 
fixes #153 

## Type of Pull Request

- [ ] Adding a feature
- [x] Fixing a bug
- [ ] Maintaining documents
- [ ] Others ()

## Verify the followings

- [x] Code is up-to-date with the `main` branch
- [x] No build errors after `npm run build`
- [x] No lint errors after `npm run lint`
- [x] No errors on using `charites help` globally
- [x] Make sure all the existing features working well
- [x] Have you added at least one unit test if you are going to add new feature?
- [x] Have you updated documentation?

Refer to [CONTRIBUTING.MD](https://github.com/unvt/charites/tree/master/.github/CONTRIBUTING.md) for more details.

### CODE REVIEW

**Comment by JinIgarashi** [comment]
@ubukawa let's see whether this PR works

**Comment by ubukawa** [comment]
It seems that "build / build (14.x, windows-latest) (pull_request) Failing".
I will join the meeting in 5 mins and will be back.
Thank you once again for your kind contribution!

**Comment by JinIgarashi** [comment]
@ubukawa could you rerun that failed job, please?

**Comment by smellman** [comment]
@JinIgarashi I just rerun that failed jobs.

**Review by ubukawa — APPROVED** [review]

**Pull request merged**
