### PR TITLE
Fix/serve command options

### LINKED ISSUE #58: Can not use `--provider` and `--mapbox-access-token`
When I use mapbox style with `charites serve style.yml --provider mapbox --mapbox-access-token my-access-token`

It will display error in console in debug tool of Google Chrome.

```
evented.js:140 Error: An API access token is required to use Mapbox GL. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes
    at ajax.js:183
```

### PR DESCRIPTION
**Pull request by JinIgarashi**
@naogify fixed #58 now. I have shift both of parameters from global to specific `server` command options because `provider` and `mapbox-access-token` options are not used in other commands rather than `serve`.

I don't think both of them are required for `init`, `convert` and `build` commands.

The below is new usage of `serve` command.
```bash
charites serve -h
Usage: charites serve [options] <source>
serve your map locally
Options:
  --provider [provider]                      your map service. e.g. `mapbox`, `geolonia`
  --mapbox-access-token [mapboxAccessToken]  Access Token for the Mapbox
  -h, --help 
```

In addition, I have added all subcommands usage on README.md.

### CODE REVIEW

**Review by naogify — CHANGES_REQUESTED** [review]
@JinIgarashi 
Thank you! Could you add the test for it?

**Comment by JinIgarashi** [comment]
@naogify Could you just merge this PR if serve command works well with optional parameters? The aim of this PR is fixing bug raised by issue #58.
Unfortunately, as you know, existing source code of serve command is not sufficient to write unit test. It may be required to change and refactor significantly in order to make test cases. It may take time to implement tests.

I have already created another issue #62 for unit test. I would like to implement unit tests for serve command together with refactoring in another PR. Does it make sense?

**Comment by JinIgarashi** [comment]
@naogify I noticed `--provider` option is also used in `build` command. Added CLI option for build and updated README.md

**Comment by naogify** [comment]
@JinIgarashi 
Thank you! Sorry for late reply. I will take a time to check it later!

**Review by naogify — APPROVED** [review]
@JinIgarashi 
Thank you. LGTM!

**Pull request merged**
