### PR TITLE
updated copyright in LICENSE file

### PR DESCRIPTION
**Pull request by JinIgarashi**
@ubukawa, @hfu, @miya0001 , I have updated copyright of LICENSE file now.

### CODE REVIEW

**Review by hfu — APPROVED** [review]
I welcome this update with great respect if it is OK for Geolonia Inc. 

In future, we might want to refine how UNVT community should credit ourselves, like "The United Nations Vector Tile Toolkit **contributors**" or "The United Nations Vector Tile Toolkit **community**". I believe that we can discuss it as a separate issue. 

Thanks!

**Comment by ubukawa** [comment]
Thank you so much! I also think the idea from @hfu  is also great and I support it.

**Comment by JinIgarashi** [comment]
@hfu I think it is good idea to have contributors list in the repository. I will create an issue for this.

**Comment by JinIgarashi** [comment]
@hfu @ubukawa I created this issue https://github.com/unvt/charites/issues/67

**Pull request merged**
