### PR TITLE
Added checkboxes for tileboundaries and collisionboxes and padding

### LINKED ISSUE #69: An idea about "serve" function.
For your future consideration, I want to share my idea.
(This is JUST for your information ;D)

I just thought it would be useful if we could have an option to add tile boundaries and collision boxes for styling work when the charites serves the live preview..
Specifically, we could have an option to add the following two lines somewhere in the app.js.

map.showTileBoundaries = true;
map.showCollisionBoxes = true;

If so, we can see the tile boundary and collision boxes during our style editing work.
(It will be optional.)

Thank you for your attention.
I wish I could develop such function by myself...

### PR DESCRIPTION
**Pull request by JinIgarashi**
@ubukawa @naogify 

## Description

fix #69. Could you confirm and merge it?

added the following three checkboxes at top-left of screen.
- added showTileBoundaries
- added showCollisionBoxes
- added setShowPadding

Also, added navigation control at top-right of screen.

image

## Type of Pull Request

- [x] Adding a feature
- [ ] Fixing a bug
- [ ] Maintaining documents
- [ ] Others ()

## Verify the followings

- [x] Code is up-to-date with the `main` branch
- [x] No build errors after `npm run build`
- [x] No lint errors after `npm run lint`
- [x] No errors on using `charites help` globally
- [x] Make sure all the exsiting features working well

Refer to [CONTRIBUTING.MD](https://github.com/unvt/charites/tree/master/.github/CONTRIBUTING.md) for more details.

### CODE REVIEW

**Comment by ubukawa** [comment]
I have checked it, and confirmed that new function worked well in the live preview.
I think the collision box in particular would be helpful to confirm the order of the layers, etc.

Thank you so much. Can I merge it to the main branch??

2021-12-18-charites

**Comment by ubukawa** [comment]
I have checked it, and confirmed that new function worked well in the live preview.
I think the collision box in particular would be helpful to confirm the order of the layers, etc.

Thank you so much. Can I merge it to the main branch??

2021-12-18-charites

**Comment by ubukawa** [comment]
It is really nice. Thank you so much!!

**Comment by JinIgarashi** [comment]
@ubukawa Thank you for checking. Could you merge it into main branch? I also believe these features will help users style map.

**Review by ubukawa — APPROVED** [review]
Thank you!

**Pull request merged**
