### PR TITLE
Editing the document (revise install, and adding an example in usage)

### PR DESCRIPTION
**Pull request by ubukawa**
Thank you for submitting a pull request!

## Description

I have edited the documentation. I revised install chapter, and adding an example in usage chapter. Dear @JinIgarashi , I only edited the source, so please build html by using sphinx if this PR is okay for you.

## Type of Pull Request

- [ ] Adding a feature
- [ ] Fixing a bug
- [x] Maintaining documents
- [ ] Others ()

## Verify the followings

- [ n/a] Code is up-to-date with the `main` branch
- [ n/a] No build errors after `npm run build`
- [ n/a] No lint errors after `npm run lint`
- [ n/a] No errors on using `charites help` globally
- [ n/a] Make sure all the existing features working well
- [ n/a] Have you added at least one unit test if you are going to add new feature?
- [x] Have you updated documentation?

Refer to [CONTRIBUTING.MD](https://github.com/unvt/charites/tree/master/.github/CONTRIBUTING.md) for more details.

### CODE REVIEW

**Review by JinIgarashi — COMMENTED** [review]
@ubukawa PR looks fine to me. You can merge it to main branch. My permission on charites was removed long time ago. I have no longer access to commit this project.

HTML will be automatically built and synchronized with transifex by Github Actions. If you would like to add Japanese translation, feel free to join transifex project.

**Comment by ubukawa** [comment]
Dear @JinIgarashi ,
Thank you very much for your kind confirmation! 
I see, then I will wait for some one approves this PR. I did not know html is automatically built. Thank you for this.

I would be happy to add Japanese translation for this. 
If possible, please teach me how I can edit it in the transifex project?

Thank you!!

**Comment by JinIgarashi** [comment]
@ubukawa FYI
https://www.transifex.com/unvt/charites-docs

**Comment by JinIgarashi** [comment]
@ubukawa Maybe I can transfer my admin permission on transifex to you. It is difficult for me to maintain charites documentation without having rights on GitHub project

**Review by keichan34 — APPROVED** [review]

**Pull request merged**
