### PR TITLE
Support for sprites on serve

### LINKED ISSUE #62: Add unit test for `serve` command
Unit test for `serve` command is required.

### LINKED ISSUE #137: Support for sprites in the serve command
**Is your feature request related to a problem? Please describe.**
`charites build` can build sprites, but `charites serve` cannot serve them.

**Describe the solution you'd like**
`charites serve` should serve sprites the same way the build command can create them. `charites serve` should reload the sprites when they've been updated, the same way the style updates (this may need some custom mapboxgl/maplibregl work) 

**Describe alternatives you've considered**
Now, the only real alternative is to have them hosted on another server, which really isn't a good alternative. Sometimes I find myself running build and then using `python -m http.server` or something like that.

**Additional context**
The sprites feature needs more documentation (#115) and probably should be thought about in terms of consistency and what a feature-complete sprites feature integrated with charites would look and feel like. For example, I could bolt on sprite serving support for `serve`, but because `build` only accepts the `-i` and `-o` arguments for spritesheet generation, `serve` would need to rely on those options as well. Ideally, these options would be set in the main `style.yml` or some kind of other file like `sprites.yml` (there has been some discussion about this in #47 and https://github.com/unvt/charites/issues/36#issuecomment-968788504)

### PR DESCRIPTION
**Pull request by keichan34**
Closes #137, closes #62 

When writing sprite support, I saw that there were no tests for the charites serve command, so I added some simple tests. While there were initially tests in #80, they were removed before merging because of some timeout issue. I think I've resolved those issues in this PR.

## Description

Adds sprite support to the `serve` command. Uses the same `--sprite-input` command line option as `build`.

## Type of Pull Request

- [x] Adding a feature
- [ ] Fixing a bug
- [ ] Maintaining documents
- [ ] Others ()

## Verify the followings

- [x] Code is up-to-date with the `main` branch
- [x] No build errors after `npm run build`
- [x] No lint errors after `npm run lint`
- [x] No errors on using `charites help` globally
- [x] Make sure all the existing features working well
- [x] Have you added at least one unit test if you are going to add new feature?
- [x] Have you updated documentation?

### CODE REVIEW

**Review by smellman — APPROVED** [review]
LGTM!

**Review by naogify — CHANGES_REQUESTED** [review]
@keichan34 
Thank you! I find this feature very useful for map styling.

Sorry for the detail, but even though I have an `icons` directory, when I run `charites serve style.yml`, the icons do not show up on the map.

If user has an `icons` directory, I think charites should show local icons without explicitly specifying `--sprite-input`.

**Comment by keichan34** [comment]
@naogify 

> If user has an icons directory, I think charites should show local icons without explicitly specifying --sprite-input.

I agree. But, I don't think it's in the scope of this PR. I think that `charites serve` and `charites build` should have the same interface for building sprites -- this is a big part of why issues like #115 and #47 exist. I've opened an issue (#146) about unifying the interface and maybe specifying a special key in `style.yml` that indicates that sprites should be built, so sprites could be built automatically without specifying `--sprite-input` both on serve and build.

**Comment by naogify** [comment]
@keichan34 
I understand it. I think #146 is nice idea!  We have so much command line options right now. Thank you!

**Review by naogify — APPROVED** [review]
LGTM!

**Pull request merged**
