### PR TITLE
added maplibre-gl-legend and mapbox-gl-legend

### PR DESCRIPTION
**Pull request by JinIgarashi**
@ubukawa @hfu @naogify  Could you merge this PR to main?

## Description

Add features related to #95 

The preview will be like the below screenshot. I hope this will help edit style.

Note. This feature is only available for maplibre and mapbox. It does not support geolonia.

スクリーンショット 2022-03-19 9 23 13

## Type of Pull Request

- [x] Adding a feature
- [ ] Fixing a bug
- [ ] Maintaining documents
- [ ] Others ()

## Verify the followings

- [x] Code is up-to-date with the `main` branch
- [x] No build errors after `npm run build`
- [x] No lint errors after `npm run lint`
- [x] No errors on using `charites help` globally
- [x] Make sure all the exsiting features working well
- [x] Have you added at least one unit test if you are going to add new feature?
- [x] Have you updated documentation?

Refer to [CONTRIBUTING.MD](https://github.com/unvt/charites/tree/master/.github/CONTRIBUTING.md) for more details.

### CODE REVIEW

**Review by ubukawa — APPROVED** [review]
Thank you! I think this is really nice.
We are using watergis/maplibre-gl-legend, so I just want to clarify if we need to add any copyright text. 
It is MIT and developed by @JinIgarashi , so it might not be necessary.. This comment is just for your consideration.

**Comment by JinIgarashi** [comment]
@ubukawa Thank you for consideration. It is no problem to use my plugin without any copyright text.

**Comment by ubukawa** [comment]
Thank you @JinIgarashi  for your kind clarification.
I am ready to merge this.

Dear @hfu and @naogify , please let us know if you have any comments.
I will wait for a few days just in case, and merge this PR to main. Thank you.
Have a nice day!

**Review by naogify — APPROVED** [review]
@JinIgarashi 
Thank you! LGTM 👍

**Pull request merged**
